### ISSUE TITLE
Lower LI icons don't toggle 

### ISSUE THREAD

**Issue by alexo-a** [laurenceokite/hop-to#15]
Bob and I both saw this. Items 0 through 3 all have this work, but 4 through x don't function correctly. Note that only those first 4 items are shown initially. Maybe the icon toggle stuff only applies to those items that are _initially visible_?

**Comment by laurenceokite** [comment]
fixed: added positon: relative; to .checkbox. .checkbox-element was getting its position: absolute; relative to the page rather than the container.
