### ISSUE TITLE
Add div for Starting Location

### ISSUE THREAD

**Issue by alexo-a** [laurenceokite/hop-to#9]
Allow user to input via current location or provided address where they'd like the trip to start (and end) at.

**Comment by alexo-a** [comment]
Put this button/divs in the area right of the Breweries/Tour toggle, only when the user is on the Tour

**Comment by TheBobbyLlama** [comment]
When this div closes, it will need to call into Bing Maps API to get latitude/longitude, and fill them into _startingLatitude_ and _startingLongitude_.  Then it can call refreshMap() to update the tour route.

You can use the API call in initialize() as a guide.  The div should also use the existing _starting_ address elements to store and retrieve from.
